# Generated by Django 6.0.3 on 2026-03-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('mrp', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('delivery_time', models.CharField(default='1-2 Days', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
