# Generated by Django 6.0.3 on 2026-03-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om_malsale_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack_discount_3',
            field=models.IntegerField(blank=True, help_text='3 pack % off (8%)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_discount_6',
            field=models.IntegerField(blank=True, help_text='6 pack % off (12%)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_price_3',
            field=models.FloatField(blank=True, help_text='3 pack TOTAL price (₹125 for Jeera)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_price_6',
            field=models.FloatField(blank=True, help_text='6 pack TOTAL price (₹240 for Jeera)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_profit_3',
            field=models.FloatField(blank=True, help_text='3 pack profit (₹15)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_profit_6',
            field=models.FloatField(blank=True, help_text='6 pack profit (₹30)', null=True),
        ),
    ]
