# Generated by Django 6.0.3 on 2026-03-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('om_malsale_app', '0002_product_pack_discount_3_product_pack_discount_6_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pack_discount_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pack_discount_6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pack_price_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pack_price_6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pack_profit_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pack_profit_6',
        ),
    ]
