# Generated by Django 6.0.3 on 2026-03-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om_malsale_app', '0004_order_rename_price_product_pack1_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
