# Generated by Django 6.0.3 on 2026-03-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om_malsale_app', '0005_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.TextField(default=''),
        ),
    ]
