# Generated by Django 5.1 on 2026-10-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om_malsale_app', '0008_product_discount_percent_product_discount_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(default='200g', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack1_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack3_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack6_price',
            field=models.FloatField(default=0),
        ),
    ]
