# Generated by Django 5.1 on 2026-10-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('om_malsale_app', '0009_product_sale_price_product_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pack1_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pack3_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pack6_price',
        ),
    ]
