# Generated by Django 5.1 on 2026-10-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om_malsale_app', '0010_remove_product_pack1_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('out_for_delivery', 'Out for Delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
